server:
  port: 9001

spring:
  application:
    name: order-microservice-group # 应用名称，会在Eureka中显示
  mvc:
    servlet:
      load-on-startup: 1
    static-path-pattern: /static/**
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud_combined_db?characterEncoding=utf-8&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: 19926172xz
  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: HTML5
  cloud:
    circuitbreaker:
      hystrix:
        enabled: true

mybatis:
  mapper-locations: mapper/*.xml

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka
  instance:
    prefer-ip-address: true # 当调用getHostname获取实例的hostname时，返回ip而不是host名称
    ip-address: localhost # 指定自己的ip信息，不指定的话会自己寻找

feign:
  hystrix:
    enabled: true # 允许feign的降级操作

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
      isolation:
        thread:
          timeoutInMilliseconds: 5000
      circuitBreaker:
        enabled: true
        requestVolumeThreshold: 5   # 该属性设置滚动窗口中将使断路器跳闸的最小请求数量

management:
  endpoint:
    health:
      show-details: always #显示熔断器详细信息 http://127.0.0.1:8001/actuator/health
  endpoints:
    web:
      exposure:
        include: "*"

#集群化监控配置
turbine:
  instanceUrlSuffix: /hystrix.stream  #没有的话会出现异常
  aggregator:
    clusterConfig: default
  appConfig: order-microservice-group
  cluster-name-expression: "'default'"