server:
  port: 8001

spring:
  application:
    name: stock-microservice-group # 应用名称，会在Eureka中显示

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8000/eureka
  instance:
    prefer-ip-address: true # 当调用getHostname获取实例的hostname时，返回ip而不是host名称
    ip-address: 127.0.0.1 # 指定自己的ip信息，不指定的话会自己寻找
